#############################################################################
# Makefile for building: spacejunk
# Generated by qmake (2.01a) (Qt 4.6.2) on: Mon Apr 23 16:59:54 2012
# Project:  spacejunk.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile spacejunk.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = game.cpp \
		hpackchgobj.cpp \
		hpackobj.cpp \
		hpackshyobj.cpp \
		junkobj.cpp \
		main.cpp \
		missileobj.cpp \
		obj.cpp \
		planetobj.cpp \
		playerobj.cpp \
		propelobj.cpp \
		shootmobj.cpp \
		spawnerobj.cpp \
		sunobj.cpp \
		unobtainchgobj.cpp \
		unobtainobj.cpp \
		unobtainshyobj.cpp 
OBJECTS       = game.o \
		hpackchgobj.o \
		hpackobj.o \
		hpackshyobj.o \
		junkobj.o \
		main.o \
		missileobj.o \
		obj.o \
		planetobj.o \
		playerobj.o \
		propelobj.o \
		shootmobj.o \
		spawnerobj.o \
		sunobj.o \
		unobtainchgobj.o \
		unobtainobj.o \
		unobtainshyobj.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		spacejunk.pro
QMAKE_TARGET  = spacejunk
DESTDIR       = 
TARGET        = spacejunk

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: spacejunk.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile spacejunk.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile spacejunk.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/spacejunk1.0.0 || $(MKDIR) .tmp/spacejunk1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/spacejunk1.0.0/ && $(COPY_FILE) --parents game.h hpackchgobj.h hpackobj.h hpackshyobj.h junkobj.h missileobj.h obj.h planetobj.h playerobj.h propelobj.h shootmobj.h spawnerobj.h sunobj.h unobtainchgobj.h unobtainobj.h unobtainshyobj.h .tmp/spacejunk1.0.0/ && $(COPY_FILE) --parents game.cpp hpackchgobj.cpp hpackobj.cpp hpackshyobj.cpp junkobj.cpp main.cpp missileobj.cpp obj.cpp planetobj.cpp playerobj.cpp propelobj.cpp shootmobj.cpp spawnerobj.cpp sunobj.cpp unobtainchgobj.cpp unobtainobj.cpp unobtainshyobj.cpp .tmp/spacejunk1.0.0/ && (cd `dirname .tmp/spacejunk1.0.0` && $(TAR) spacejunk1.0.0.tar spacejunk1.0.0 && $(COMPRESS) spacejunk1.0.0.tar) && $(MOVE) `dirname .tmp/spacejunk1.0.0`/spacejunk1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/spacejunk1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

game.o: game.cpp game.h \
		playerobj.h \
		obj.h \
		sunobj.h \
		planetobj.h \
		unobtainobj.h \
		unobtainshyobj.h \
		unobtainchgobj.h \
		hpackobj.h \
		hpackshyobj.h \
		hpackchgobj.h \
		junkobj.h \
		spawnerobj.h \
		shootmobj.h \
		missileobj.h \
		propelobj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o game.o game.cpp

hpackchgobj.o: hpackchgobj.cpp hpackchgobj.h \
		hpackobj.h \
		obj.h \
		game.h \
		playerobj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hpackchgobj.o hpackchgobj.cpp

hpackobj.o: hpackobj.cpp hpackobj.h \
		obj.h \
		game.h \
		playerobj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hpackobj.o hpackobj.cpp

hpackshyobj.o: hpackshyobj.cpp hpackshyobj.h \
		hpackobj.h \
		obj.h \
		game.h \
		playerobj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hpackshyobj.o hpackshyobj.cpp

junkobj.o: junkobj.cpp junkobj.h \
		obj.h \
		game.h \
		playerobj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o junkobj.o junkobj.cpp

main.o: main.cpp game.h \
		playerobj.h \
		obj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

missileobj.o: missileobj.cpp missileobj.h \
		obj.h \
		game.h \
		playerobj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o missileobj.o missileobj.cpp

obj.o: obj.cpp obj.h \
		game.h \
		playerobj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj.o obj.cpp

planetobj.o: planetobj.cpp planetobj.h \
		obj.h \
		game.h \
		playerobj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o planetobj.o planetobj.cpp

playerobj.o: playerobj.cpp playerobj.h \
		obj.h \
		propelobj.h \
		game.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o playerobj.o playerobj.cpp

propelobj.o: propelobj.cpp propelobj.h \
		obj.h \
		game.h \
		playerobj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o propelobj.o propelobj.cpp

shootmobj.o: shootmobj.cpp shootmobj.h \
		obj.h \
		game.h \
		playerobj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o shootmobj.o shootmobj.cpp

spawnerobj.o: spawnerobj.cpp spawnerobj.h \
		obj.h \
		game.h \
		playerobj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o spawnerobj.o spawnerobj.cpp

sunobj.o: sunobj.cpp sunobj.h \
		obj.h \
		game.h \
		playerobj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sunobj.o sunobj.cpp

unobtainchgobj.o: unobtainchgobj.cpp unobtainchgobj.h \
		unobtainobj.h \
		obj.h \
		game.h \
		playerobj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unobtainchgobj.o unobtainchgobj.cpp

unobtainobj.o: unobtainobj.cpp unobtainobj.h \
		obj.h \
		game.h \
		playerobj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unobtainobj.o unobtainobj.cpp

unobtainshyobj.o: unobtainshyobj.cpp unobtainshyobj.h \
		unobtainobj.h \
		obj.h \
		game.h \
		playerobj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unobtainshyobj.o unobtainshyobj.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

